name: expandable_widgets
description: A package provides expandable widgets for Flutter, written in 100% Dart.
version: 1.0.3+1
homepage: https://github.com/fatihozkan-github/ExpandableWidgets

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background.png
